### ISSUE TITLE
Metoda sendInvoice(int $id)

### ISSUE THREAD

**Issue by ShinJii89** [mariusz-zajac/fakturownia#1]
Cześć,
Po aktualizacji z wersji 1.1.0 do najnowszej coś się stało u Ciebie przy metodzie `sendInvoice(int $id)` 
Jeśli użytkownik np. ma nieopłacone konto na fakturowni to wiadomo, zwraca błąd przy createInvoice, ale ja miałem tak zrobione, że nawet przy errorze dawałem sendInvoice po prostu z pustym ID (nie sprawdzałem czy jest puste czy nie) i skrypt śmigał poprawnie i wykonywał kolejne operacje po komendzie sendInvoice, a teraz się wysypuje (nie sprawdzałem ale zgaduję, że error 500) - coś zmieniałeś? 
Oczywiście już to obszedłem ale trochę nerwów mnie to dzisiaj kosztowało w zlokalizowaniu :D

Generalnie piszę to jako ciekawostka - nie wiem czy to u Ciebie się coś wysypuje czy może fakturownia przy nie opłaconym koncie zwraca coś takiego, że przez to się wysypuje :) po prostu chodzi mi, że wcześniej działało.

**Comment by mariusz-zajac** [comment]
Cześć,
dzięki za zgłoszenie. W najnowszej wersji (1.3.0) wprowadziłem we wszystkich metodach typehinty parametrów i to prawdopodobnie powoduje u Ciebie błąd. Teraz metoda `sendInvoice` oczekuje, aby parametr `$id` był typu `int` i jeśli dostaje puste ID to się wywala. Rozwiązaniem byłoby sprawdzenie czy `createInvoice` wykonało się poprawnie i dopiero wtedy wywołanie `sendInvoice`, np.:
```
$response = $fakturownia->createInvoice($invoiceData);
if ($response->isSuccess()) {
    $invoice = $response->getData();
    $fakturownia->sendInvoice($invoice['id']);
}
```
Gdybyś jeszcze miał jakieś problemy, to daj znać.

**Comment by ShinJii89** [comment]
Witaj ponownie @mariusz-zajac ,
Fakturownia zmieniła coś w API i można od kilku dni tworzyć tokeny bez prefiksu, który jak wiadomo odpowiadał za domenę w fakturownia.pl i... mając swoją platformę gdzie użytkownicy mogą konfigurować swoje własne konta fakturownia.pl no... niektórzy mają już API stworzone bez tego prefiksu i wtedy Twój skrypt nie działa, wywala error 500 przy błędnym tokenie.
Z tego co widzę winowajcą jest ta funkcja
```
public function isValidTokenOrFail($token): void
    {
        // check pattern: token_hash/username
        $isValid = is_string($token) && 1 === preg_match('~^[^/]+/[^/]+$~', $token);

        if (!$isValid) {
            throw new InvalidTokenException();
        }
    }
```
Przy tym się wykłada jak jest błędny token.

Wyświetla mi error 500 i:

> Fatal error: Uncaught Abb\Fakturownia\Exception\InvalidTokenException: Invalid Fakturownia API token in xxx/includes/libs/fakturownia/vendor/abb/fakturownia/src/FakturowniaTokenValidator.php:28 Stack trace: #0 xxx/includes/libs/fakturownia/vendor/abb/fakturownia/src/Fakturownia.php(41): Abb\Fakturownia\FakturowniaTokenValidator->isValidTokenOrFail('g') #1 xxx/ajax/admin/ustawienia-ksiegowosc.ajax.php(206): Abb\Fakturownia\Fakturownia->__construct('g') #2 {main} thrown in xxx/includes/libs/fakturownia/vendor/abb/fakturownia/src/FakturowniaTokenValidator.php on line 28

**Comment by mariusz-zajac** [comment]
Cześć.
Rozwiązanie na teraz: Możesz złapać ten wyjątek i w jakimś komunikacie poprosić klientów o wygenerowanie tokenu z prefiksem (Fakturownia daje taką możliwość), np.:
```
try {
    $fakturownia = new \Abb\Fakturownia\Fakturownia('fakturownia_api_token');
    // ...
} catch (\Abb\Fakturownia\Exception\InvalidTokenException $e) {
    $message = 'Proszę wprowadzić token z prefiksem. Możesz go wygenerować w serwisie Fakturownia.pl';
    // ...
}
```
W kolejnej wersji uwzględnię ten przypadek. Zajmę się tym najszybciej jak to możliwe.

**Comment by ShinJii89** [comment]
> Cześć.
> Rozwiązanie na teraz: Możesz złapać ten wyjątek i w jakimś komunikacie poprosić klientów o wygenerowanie tokenu z prefiksem (Fakturownia daje taką możliwość), np.:
> 
> ```
> try {
>     $fakturownia = new \Abb\Fakturownia\Fakturownia('fakturownia_api_token');
>     // ...
> } catch (\Abb\Fakturownia\Exception\InvalidTokenException $e) {
>     $message = 'Proszę wprowadzić token z prefiksem. Możesz go wygenerować w serwisie Fakturownia.pl';
>     // ...
> }
> ```
> 
> W kolejnej wersji uwzględnię ten przypadek. Zajmę się tym najszybciej jak to możliwe.

O, tego mi było trzeba, nie mogłem sobie poradzić z tym catchem właśnie :D dzięki!

**Comment by mariusz-zajac** [comment]
Dodałem w dokumentacji informację o obsługiwanych tokenach oraz bardziej szczegółowy komunikat w exceptionie. Nie było więcej zgłoszeń na ten temat. Zamykam wątek.
